package com.devforge.document.domain;

import com.devforge.document.contract.DocumentType;
import com.devforge.shared.domain.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.util.UUID;

/**
 * A page of documentation inside one workspace.
 *
 * <p>{@code workspaceId} is a bare identifier, not a {@code @ManyToOne} to
 * {@code Workspace}. The foreign key still exists in the database, so integrity
 * and cascading deletes are unaffected, but the object model no longer spans two
 * modules — which means the document module compiles, loads, and tests without
 * the workspace module's persistence classes.
 *
 * <p>The {@code search_vector} column is generated by PostgreSQL and
 * intentionally left unmapped, so Hibernate never attempts to write it.
 */
@Entity
@Table(
        name = "documents",
        uniqueConstraints = @UniqueConstraint(columnNames = {"workspace_id", "slug"})
)
public class Document extends BaseEntity {

    @Column(name = "workspace_id", nullable = false, updatable = false)
    private UUID workspaceId;

    @Column(nullable = false, length = 500)
    private String title;

    @Column(nullable = false, length = 200)
    private String slug;

    @Column(nullable = false, columnDefinition = "TEXT")
    private String content = "";

    @Enumerated(EnumType.STRING)
    @Column(name = "document_type", nullable = false, length = 50)
    private DocumentType documentType;

    /**
     * Holds this page back from the public site even while its workspace is
     * published.
     *
     * <p>Defaults to false: publishing a workspace exposes its pages, and the
     * client makes that visible rather than leaving it implicit.
     */
    @Column(nullable = false)
    private boolean internal = false;

    protected Document() {
    }

    public Document(
            UUID workspaceId,
            String title,
            String slug,
            String content,
            DocumentType documentType,
            boolean internal
    ) {
        this.workspaceId = workspaceId;
        this.title = title;
        this.slug = slug;
        this.content = content == null ? "" : content;
        this.documentType = documentType;
        this.internal = internal;
    }

    public UUID getWorkspaceId() {
        return workspaceId;
    }

    public String getTitle() {
        return title;
    }

    public String getSlug() {
        return slug;
    }

    public String getContent() {
        return content;
    }

    public DocumentType getDocumentType() {
        return documentType;
    }

    public boolean isInternal() {
        return internal;
    }

    /** Applies a whole edit at once, keeping the entity's state consistent. */
    public void revise(
            String title,
            String slug,
            String content,
            DocumentType documentType,
            boolean internal
    ) {
        this.title = title;
        this.slug = slug;
        this.content = content == null ? "" : content;
        this.documentType = documentType;
        this.internal = internal;
    }

    public boolean belongsTo(UUID workspaceId) {
        return this.workspaceId.equals(workspaceId);
    }
}
